version: '3'
services:
    app:
        build: .
        ports:
            - "3000":"3000"
        links:
            - mongo
        depends_on:
            - mongo
        working_dir: /home/node/app
        volumes:
            - .:/home/node/app
        environment:
            - NODE_ENV=development
        command: "gulp"
    mongo:
        image: mongo:3.2
        volumes:
            - mongo-data:/data/db
        expose:
            - "27017"
volumes:
    mongo-data:
